# Page settings
baseurl = "https://phytago.github.io/"
title = "PHYTAGO - Delikatessen aus ökologischer Kreislaufproduktion"
languageCode = "en-us"
theme = "hugo-elate-theme"

# Theme Params
[params]

  # Meta Section
  custom_css = ["/css/custom1.css", "/css/custom2.css"]
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "**P H Y T A G O**"
    intro = "Produkte"
    services = "Produktion"
    counters = "Philosophie"
    about = "Über uns"
    testimonials = "Das Team"
    work = "Referenzen"
    contact = "Kontakt"
    account = "Mein Phytago"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    #[[menu.prepend]]
    #  url = "/verwaltung/kundenbereich"
    #  name = "Mein Phytago"
    #  weight = 12

    #[[menu.postpend]]
    #  url = "/verwaltung/kundenbereich"
    #  name = "Mein Phytago"
    #  weight = 12

  # Hero section
  [params.hero]
    title = "Wir pflanzen Pflanzen"
    subtitle1 = ""
    subtitle2 = ""
    subtitle3 = ""
    subtitle4 = ""
    subtitle5 = ""

  # Intro section
  # Available icons: https://simplelineicons.com/
  [params.intro]
    title = "PRODUKTE"

    [[params.intro.item]]
      title = "Jungpflanzen"
      description = "... sind verschiedene Gemüse- und Gewürzsorten in ihrer frühen Entwicklungsphase mit hohen Aromen- als auch Vitaminkonzentrationen"
      url = "/produkte/jungpflanzen"
      button = "Jungpflanzen"
      icon = "icon-plant"
      img = "Microgreens.jpg"
      herovideo = "home_jungpflanzen.mp4"
      videoposition = "0"

    [[params.intro.item]]
      title = "Gourmetpilze"
      description = "... sind verschiedene besonders schmackhafte und seltene Pilzsorten mit beispielsweise herzhaften, nussigen oder auch süßlichen Aroma"
      url = "/produkte/gourmetpilze"
      button = "Gourmetpilze"
      icon = "icon-diamond"
      img = "Pilze.jpg"
      herovideo = "home_gourmetpilze.mp4"
      videoposition = "0"

    [[params.intro.item]]
      title = "Vitalpulver"
      description = "... sind aus unseren frischen Lebensmitteln erzeugte natürlich Pulver, welche individualisiert entsprechend der Bedürfnisse zusammengestellt werden"
      url = "/produkte/vitalpulver"
      button = "Vitalpulver"
      icon = "icon-diamond"
      img = "Gewuerze.jpg"
      herovideo = "home_vitalpulver.mp4"
      videoposition = "0"

  # Work section
  [params.work]
    enable = false
    menu = false
    title = "a"
    description = "a"
    footertext = "a"

    [[params.work.row]]
      img = "b"
      alt = "b"
      title = "b"
      subtitle = "b"

    [[params.work.row]]
      img = "b"
      alt = "b"
      title = "b"
      subtitle = "b"

    [[params.work.row]]
      img = "b"
      alt = "b"
      title = "b"
      subtitle = "b"

  # Testimonials Section
  [params.testimonials]
    enable = true
    menu = true
    title = "Das TEAM"
    description = "Mit fachlichem Wissen und Kenntnisspezialisierungen für Sie erreichbar:"


    [[params.testimonials.item]]
      quote = "Der Betriebswirt"
      person = 'Nico'
      img = "team1.png"
      alt = ""

    [[params.testimonials.item]]
      quote = "Die Ökologin"
      person = 'Céline'
      img = "team2.png"
      alt = ""

    [[params.testimonials.item]]
      quote = "Der Ingenieur"
      person = 'Robert'
      img = "team4.png"
      alt = ""

    [[params.testimonials.item]]
      quote = "Der Informatiker"
      person = 'Henry'
      img = "team3.png"
      alt = ""

    [[params.testimonials.item]]
      quote = "Der Webspezialist"
      person = 'Thomas'
      img = "person1.jpg"
      alt = ""

      [[params.testimonials.item]]
        quote = "Die Basis"
        person = 'Natur'
        img = "nature.jpg"
        alt = ""


  # Services section
  [params.services]
    enable = true
    menu = true
    title = "Besonderheiten der Produktion"
    description = "Über ein innovatives Kreislaufsystem, welches mit künstlicher Intelligenz die Zuchtbereiche der verschiedenen Organismen kombiniert, werden unsere Lebensmittel frei von Pestiziden, ganzjährig mit gleichbleibend höchster Qualität produziert, wobei der Ressourcenbedarf minimal und der Geschmack maximal ist."

    [[params.services.item]]
      title = "individualisierte Versorgung"
      description = "Wunschentsprechend werden Versorgungspläne für unsere frischen getrockneten, pulverisierten und gefrosteten Lebensmittel erstellt, welche jederzeit angepasst werden können."
      icon = "icon-directions"


    [[params.services.item]]
      title = "RST - Ressource-Saving-Tool "
      description = "Mithilfe von RST‘s kann das Gewicht von Lebensmitteln im Lager ermittelt werden, sodass aufwendige Inventuren,  zu geringe Vorräte oder Wegwerf-Risiko bei Fehlbestellungen erspart bleiben. Zusätzlich kann mit RST‘s die Bestellung neuer Waren, abhängig vom Restbestand im Lager, individuell automatisiert werden."
      icon = "icon-chart"
      # puzzle

  # About section
  [params.about]
    enable = true
    menu = false
    title = "Nachhaltige und soziale Projekte"
    description = "Zu unserer Geschäftsphilosophie gehört auch der nachhaltige Umgang mit unserer aller Umwelt und die Förderung von gemeinnützigen Initiativen.&NewLine;&NewLine;"

    [params.about.video]
      enable = false
      # title = "Sieh dir das Video an!"
      icon = "icon-play2"
      url = "https://www.youtube.com/watch?v=mCSrPOwjzr0"

    [[params.about.item]]
      name = "Unsere Nachhaltigkeit"
      position = ""
      description = "Für jeden Quadratmeter, welchen wir als Anbaufläche in unserem innovativen Kreislaufsystem nutzen wird ein Quadratmeter Monokultur oder ehemalige Industriefläche renaturiert und zu einem öffentliche Permakultur-Park umgewandelt."
      img = "nachhalt.jpg"
      alt = ""
      social = [
        ["icon-frame", "jetzt unterstützen"]
      ]

    [[params.about.item]]
      name = "Unser soziales Engagement"
      position = ""
      description = "Wir helfen mit frischesten Lebensmittelspenden aus unserer Produktion sozialen Einrichtungen, wie zum Beispiel Waisenheimen, Pflegeeinrichtungen und Seniorenzentren."
      img = "sozial.jpg"
      alt = ""
      social = [
        ["icon-umbrella", "jetzt unterstützen"]
      ]

  # Counters section
  [params.counters]
    enable = true
    menu = true
    title = "Philosophie"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Geschmack"
      icon = "icon-emotsmile"
      from = 0
      to = 100
      interval = 1
      speed = 200

    [[params.counters.item]]
      description = "kürzere Transportwege"
      icon = "icon-plane"
      from = 0
      to = 97
      interval = 1
      speed = 200

    [[params.counters.item]]
      description = "weniger Wasser"
      icon = "icon-drop"
      from = 0
      to = 96
      interval = 1
      speed = 200

    [[params.counters.item]]
      description = "weniger Dünger"
      icon = "icon-graph"
      from = 0
      to = 93
      interval = 1
      speed = 200

    [[params.counters.item]]
      description = "Pestizide"
      icon = "icon-close"
      from = 100
      to = 0
      interval = 1
      speed = 200

    [[params.counters.item]]
      description = "Abfall"
      icon = "icon-trash"
      from = 100
      to = 0
      interval = 1
      speed = 200

    [[params.counters.item]]
       description = "chemischer Dünger"
       icon = "icon-chemistry"
       from = 100
       to = 0
       interval = 1
       speed = 200

     [[params.counters.item]]
        description = "Ausfall"
        icon = "icon-loop"
        from = 100
        to = 0
        interval = 1
        speed = 200

  # Contact section
  [params.contact]
    enable = true
    menu = true
    map = true
    form = true
    title = "Verbinden ist Zukunft"
    description = "In einem Zeitalter der unbegrenzten Möglichkeiten freuen wir uns Potentiale zu beflügeln."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-envelope-letter", "nico.jany@web.de"],
        ["icon-call-out", "+49 0176 57842386"],
        ["icon-xing", "[Nico Jany @ Xing](https://www.xing.com/profile/Nico_Jany/cv/)"],
        ["icon-linkedin", "[Nico Jany @ LinkedIn](https://www.linkedin.com/in/nico-jany-b272211b4/)"]
      ]
      # ["icon-facebook", "facebook.link.go"],
      # ["icon-twitter", "twitter.link.go"],
      # ["icon-globe", "Persönliche Internetpräsenz"]

    name = "Ihr Name"
    email = "Ihre Email"
    phone = "Ihre Telefonnummer"
    message = "Ihre Nachricht"
    button = "Nachricht senden"

  # Footer section
  [params.footer]
    enable = true
    menu = false
    copyright = '&copy; PHYTAGO, 2020'
    links = [
        ["icon-lock", "/verwaltung/datenschutz", "Datenschutz"],
        ["icon-paperclip", "/verwaltung/agb", "AGB"],
        ["icon-people", "/verwaltung/impressum", "Impressum"]
      ]
